---
title: "Data import"
output: github_document
---
```{r}
library(tidyverse)
library(readxl)
library(haven)

```

Let's import a dataset

```{r}
litters_df =
  read.csv("data_import_examples/FAS_litters.csv")
```

Look at your data

```{r}
names(litters_df)
```
Updates the namens in litter_df

```{r}
litters_df =
  janitor::clean_names(litters_df)
```

Look at the data
```{r}
litters_df
```


Sometimes skimming data in neat?
```{r}
skimr::skim(litters_df)
```



#Fix the missing data
We can skip=5
```{r}
litters_df = 
  read.csv("data_import_examples/FAS_litters.csv", na = c("NA", ".", ""))
```
#Import Pups data
```{r}
pups_df = 
  read.csv("data_import_examples/FAS_pups.csv",
           skip = 3,
           na = c("NA", ".", ""))

pups_df=
  janitor::clean_names(pups_df)
```


# Okay waht about excel

CSVs are really great but sometimes you get a excel file
c+a+i
```{r}
mlb_df = 
  read_excel("data_import_examples/mlb11.xlsx")
```

Import LatR word counts
```{r}
fatr_df = 
  read_excel("data_import_examples/LotR_Words.xlsx")
```

##SAS?

Import the PULSE data

```{r}
pulse_df = 
  read_sas("data_import_examples/public_pulse_data.sas7bdat")

pulse_df = 
  janitor::clean_names(pulse_df)

```

###Why do i hate read.csv so much

```{r , eval=FALSE}
litters_df_base = 
  read.csv("data_import_examples/FAS_litters.csv")
```

## what about data exporting

```{r}
write.csv(fatr_df, "data_import_examples/fatr_df.csv")
```

